# Generated by Django 3.2 on 2021-04-20 15:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('product_image', models.ImageField(upload_to='media')),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('KIDDIES_FEMALE', 'KIDDIES_FEMALE'), ('MEN', 'MEN'), ('WOMEN', 'WOMEN'), ('CATEGORY', 'CATEGORY'), ('KIDDIES_MALE', 'KIDDIES_MALE')], default='CATEGORY', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
